version: '3.8'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php_stisla
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravels

  nginx:
    image: nginx:1.19-alpine
    container_name: web
    restart: unless-stopped
    ports:
      - "8005:80"

    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravels
    depends_on:
      - php
  mysql:
    image: mysql:5.7.22
    container_name: stisla-mysql
    # restart: unless-stopped
    # tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - laravels
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

networks:
  laravels:
    driver: bridge
